"""Add timestamp column to activities table

Revision ID: 81b84aa912d4
Revises: e477b0bfd369
Create Date: 2025-10-29 23:49:43.204558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b84aa912d4'
down_revision = 'e477b0bfd369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy_type', sa.String(length=50), nullable=False),
    sa.Column('energy_amount', sa.Float(), nullable=False),
    sa.Column('energy_unit', sa.String(length=50), nullable=False),
    sa.Column('co2_emission', sa.Float(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('co2_emission', sa.Float(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transport_activities')
    with op.batch_alter_table('carbon', schema=None) as batch_op:
        batch_op.drop_index('idx_user_date')
        batch_op.drop_index('ix_carbon_date')
        batch_op.drop_index('ix_carbon_user_id')

    op.drop_table('carbon')
    op.drop_table('energy_activities')
    op.drop_table('dashboard')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('emission_calculated')
        batch_op.drop_column('created_at')
        batch_op.drop_column('date')
        batch_op.drop_column('co2_emission')
        batch_op.drop_column('activity_type')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('activity_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('co2_emission', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('emission_calculated', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    op.create_table('dashboard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('energy_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('usage_kwh', sa.FLOAT(), nullable=False),
    sa.Column('duration_hours', sa.FLOAT(), nullable=True),
    sa.Column('appliance_name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('transport', sa.FLOAT(), nullable=False),
    sa.Column('energy', sa.FLOAT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date')
    )
    with op.batch_alter_table('carbon', schema=None) as batch_op:
        batch_op.create_index('ix_carbon_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_carbon_date', ['date'], unique=False)
        batch_op.create_index('idx_user_date', ['user_id', 'date'], unique=False)

    op.create_table('transport_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('distance', sa.FLOAT(), nullable=False),
    sa.Column('vehicle_model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fuel_efficiency', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transport_logs')
    op.drop_table('energy_logs')
    # ### end Alembic commands ###
